### ISSUE TITLE
Is there a way to include necessary prelude-ls code in compiled output?

### ISSUE THREAD

**Issue by ceremcem** [gkz/prelude-ls#105]
Hi, 

I'm programming an embedded device with Livescript and I want to use prelude-ls of course. The device is accepting pure Javascript codes in just a single file and it requires the code would be a few kilobytes.

Is there any possibility that we could tell `lsc` to include prelude-ls source code into de compiled (`ls -cb app.ls`) output? It should include only necessary (used) prelude-ls functions if possible.

**Comment by gkz** [comment]
I would search for a generic JavaScript dead code removal tool. I brief google found a couple of options.

**Comment by ceremcem** [comment]
If I didn't understand wrongly, you suggest including all prelude-ls (via copy and paste) and then removing unnecessary (dead code) with a separate tool, right?

**Comment by anko** [comment]
@ceremcem 

Have you tried a _minifier_ like [esmangle](https://github.com/estools/esmangle) or [UglifyJS 2](https://github.com/mishoo/UglifyJS2)? They can help minimise file size without dead code elimination. These are very easy to use, compared to dead code removal tools.

For getting everything in 1 file, I think you might want a _bundler_. Read about [browserify](http://browserify.org/), [rollup](https://github.com/rollup/rollup) or [Google's Closure Compiler](https://developers.google.com/closure/compiler/). They look for `require()` calls or `import`-statements and reorganise your JS files into one file. The last 2 can also do advanced dead code elimination.

You can of course both bundle _and_ minify for absolute minimum file size.

**Comment by ceremcem** [comment]
Right, browserify would exacly do what I want (I need to try rollup too). Thank you.
