### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by brettz9** [gkz/prelude-ls#121]
I see there hasn't been activity for a while, but might you put out a release which includes the updated `license`? As a dependency of several packages, my license checker program (licensee.js) is not able to resolve your license properly. Thanks!

**Comment by gkz** [comment]
currently it's `"license": "MIT"`, what's wrong with that/what should it be

**Comment by brettz9** [comment]
It's good as is. It's just that there hasn't been an npm release since that was updated.
