### ISSUE TITLE
empty returns true for non-empty objects

### ISSUE THREAD

**Issue by sleepyfox** [gkz/prelude-ls#76]
LiveScript 1.2.0, prelude 1.1.1 (from npm)

empty {} returns true
empty { a: 1 } returns true (when it should return false)

**Comment by farzher** [comment]
...What? Of course they're different types.
`empty` could easily tell the difference between `{}` and `[]` and `""`
There's no reason why `empty` shouldn't automatically work for everything, besides performance (which happens to be a decent reason to have separate functions).

![image](https://cloud.githubusercontent.com/assets/1005136/7439720/909b5e80-f055-11e4-8e14-8275c05fb564.png)
