### ISSUE TITLE
mean/average incorrect with nulls

### ISSUE THREAD

**Issue by atifaziz** [gkz/prelude-ls#80]
This looks wrong:

    mean [1 2 null 3] # => 1.5

And it is inconsistent with:

    mean [1 2 void 3] # => NaN

`mean`/`average` should skip `null` and `void` and exclude them from the final count.

**Comment by michaelficarra** [comment]
The behaviour should be undefined. You should be responsible for stripping your own non-numeric values from the list.

**Comment by vendethiel** [comment]
:+1: . `mean`/`average` takes a `List Int`.

**Comment by michaelficarra** [comment]
@vendethiel `List Number`, surely.

**Comment by vendethiel** [comment]
@michaelficarra You mean `Array Number`, then :P.

**Comment by michaelficarra** [comment]
Haha they're functionally the same so I don't care.

**Comment by atifaziz** [comment]
Ok, the [doc does read](http://www.preludels.com/#mean) `[Number] → Number` so one could say anything else is undefined behaviour.
KISS :+1:
