### ISSUE TITLE
zip-all does 9e9 iterations on empty list

### ISSUE THREAD

**Issue by jampekka** [gkz/prelude-ls#82]
The min-length gets 9e9 if the the args is empty (seems that there may be other corner cases too).
Actually could work just with `min-length = undefined` instead of `min-length = 9e9`.

**Comment by anko** [comment]
The [documented](http://www.preludels.com/#zip-all) function signature is

> ([a], [b], [c], ...) → [[a, b, c, ...]]

so passing `undefined` is undefined <sub>(heh)</sub> behaviour to begin with. Other functions also behave nonsensically when passed unexpected arguments.

The current consensus seems to be not to clutter the code with argument-sanity checks.

**Comment by jampekka** [comment]
Shouldn't the signature be `(a, [b], [c], ...) → [[a, b, c, ...]]` in that case?

And in general, I have to say I'm totally disagreeing with such consensus. Especially in a "prelude" library I think undefined behavior, and especially ones DoSsing the interpreter, is unacceptable.

If this really is the consensus, I think I'll go for something like `rambda` instead.

**Comment by jampekka** [comment]
To reproduce: `empty=[]; zipAll ...empty`
