### ISSUE TITLE
Docs incorrect on type of 2nd arg to Str.slice

### ISSUE THREAD

**Issue by atifaziz** [gkz/prelude-ls#86]
The signature for [`Str.slice` in docs](http://www.preludels.com/#str-slice) currently reads:

> Number → String → String

It should instead read: **Number → *Number* → String**

**Comment by gkz** [comment]
Actually it should be `Number -> Number -> String -> String`

**Comment by atifaziz** [comment]
@gkz Yep, my bad. Will fix.
