### ISSUE TITLE
slice function does not work as expected

### ISSUE THREAD

**Issue by ceremcem** [gkz/prelude-ls#96]
```
a = \hello
slice -3 -1 a  # => 'll' (as expected)
slice -3 0 a  # expected 'llo', returned '' 
```

**Comment by anko** [comment]
That seems like the expected values to me. Same in JS:

```
$ node
> "hello".slice(-3, -1)
'll'
> "hello".slice(-3, 0)
''
```

The slice range's end value `0` is referring to the beginning of the string. Slicing such that the end of the slice range comes before the beginning implies no output.

Perhaps you meant `"hello".slice(-3)` in JS, a.k.a. `slice -3 undefined, \hello` in LiveScript? That gives `'llo'`.

**Comment by ceremcem** [comment]
Yes, it turns out that `slice -3 undefined, \hello` is what I need, same as in Python's `"hello"[-3:]` and not `"hello"[-3:0]`. 

Thank you and sorry for bothering with such a question.
